//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UAT_CREATOR.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class UAT_Migration
    {
        public int Id { get; set; }
        public System.DateTime DateUATPackage { get; set; }
        public int ApplicationId { get; set; }
        public string Error { get; set; }
    
        public virtual Application Application { get; set; }
    }
}
